name: Deploy to Server

on:
  pull_request: 
    branches:
      - develop
  push:
    branches:
      - develop
      - feature/add-deployment

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
            node-version: 18
            cache: 'yarn'
            cache-dependency-path: yarn.lock
      
      - name: Install Dependencies
        run: yarn 

      - name: Build
        run: yarn build
      